import type { Metadata } from "next";
import "./globals.css";
import { raleway } from "./ui/fonts";
import NavBar from "./ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} pt-4  md:pt-12`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
